services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    depends_on:
      - db
      - es
      - selenium
    networks:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs
    ports:
      - "3000:3000"
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certificates:/certificates
      - ./frontend/certificates:/certificates/nextjs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - backend


  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: SneakSyncHub
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: es
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_SEARCH_PASSWORD}
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - backend

  selenium:
    image: selenium/standalone-firefox:latest
    container_name: selenium
    ports:
      - "4444:4444"
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - backend

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    env_file:
      - .env.docker
    command: celery -A SneakSyncHub worker --loglevel=info
    depends_on:
      - redis
    networks:
      - backend

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_beat
    command: celery -A SneakSyncHub beat -l info
    env_file:
      - .env.docker
    depends_on:
      - redis
    networks:
      - backend

  flower:
    image: mher/flower:latest
    container_name: flower
    ports:
      - "5555:5555"
    command: celery --broker=redis://redis:6379/0 flower
    depends_on:
      - redis
    networks:
      - backend




volumes:
  postgres_data:
  elasticsearch_data:

networks:
  backend:
