# Generated by Django 5.0.1 on 2024-08-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shoe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("url", models.URLField(max_length=400)),
                ("image", models.URLField(max_length=400)),
                ("article", models.CharField(max_length=200)),
                ("sizes", models.TextField()),
                ("parsed_from", models.CharField(max_length=200)),
            ],
        ),
    ]
