# Generated by Django 5.0.1 on 2024-06-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='sizes',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
