# Generated by Django 5.0.1 on 2024-06-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_shoe_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='sizes',
            field=models.CharField(max_length=400),
        ),
    ]
