# Generated by Django 5.0.1 on 2024-09-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_shoe_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoe",
            name="count",
            field=models.IntegerField(default=0),
        ),
    ]
