# Generated by Django 5.0.1 on 2024-06-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_shoe_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='sizes',
            field=models.TextField(),
        ),
    ]
