# Generated by Django 5.0.1 on 2024-09-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_shoepricehistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoe",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shoe",
            name="details",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shoe",
            name="features",
            field=models.JSONField(default=list),
        ),
    ]
