# Generated by Django 5.0.1 on 2024-09-11 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_shoe_details_remove_shoe_features_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shoe",
            old_name="benefits",
            new_name="details",
        ),
    ]
