# Generated by Django 5.0.1 on 2024-09-26 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_rename_benefits_shoe_details"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shoe",
            name="details",
        ),
    ]
