# Generated by Django 5.0.1 on 2024-10-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_shoe_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoesNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("image", models.URLField(max_length=400)),
            ],
        ),
    ]
