# Generated by Django 5.0.1 on 2024-10-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_shoesnews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoesnews",
            name="image",
            field=models.URLField(blank=True, max_length=400),
        ),
    ]
