# Generated by Django 5.0.1 on 2024-06-18 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_shoe_sizes'),
        ('members', '0003_customuser_urls_parse_list_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='scraped_articles',
            field=models.ManyToManyField(related_name='scraped_articles', to='core.shoe'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
